coverage:
  status:
    project: off
    patch: off

comment:
  require_changes: true

ignore:
  - src/Commands/**
  - src/Concerns/CanManipulateFiles.php
  - src/Concerns/CanGenerateModulePanels.php
