<?php

namespace Coolsam\Modules\Commands;

use Coolsam\Modules\Concerns\GeneratesModularFiles;
use Illuminate\Console\GeneratorCommand;
use function Laravel\Prompts\select;

class ModuleMakeFilamentPluginCommand extends GeneratorCommand
{
    use GeneratesModularFiles;

    protected $name = 'module:make:filament-plugin';

    protected $description = 'Create a new Filament Plugin class in the module';

    protected $type = 'Filament Plugin';

    protected $aliases = [
        'module:filament:plugin',
        'module:filament:make-plugin',
    ];

    protected function getRelativeNamespace(): string
    {
        return 'Filament';
    }

    protected function getStub(): string
    {
        return $this->resolveStubPath('/stubs/filament-plugin.stub');
    }

    protected function stubReplacements(): array
    {
        return [
            'moduleStudlyName' => $this->getModule()->getStudlyName(),
            'pluginId' => str($this->argument('name'))->replace('Plugin', '')->studly()->lower()->toString(),
        ];
    }

    public function handle(): ?bool
    {
        $this->ensureModule();
        return parent::handle(); // TODO: Change the autogenerated stub
    }

    public function ensureModule()
    {
        if (! $this->argument('module')) {
            $module = select('Please select the module to create the plugin in:', \Nwidart\Modules\Facades\Module::allEnabled());
            $this->input->setArgument('module', $module);
        }
    }
}
